Remove poSubDataset as it is unused in ecrgtocdataset.cpp.
ecrgtocdataset.cpp:409:24: error: private field 'poSubDataset' is not used
      [-Werror,-Wunused-private-field]


git-svn-id: https://svn.osgeo.org/gdal/trunk@35260 f0d54148-0727-0410-94bb-9a71ac55c965