Attempt to get isnan working again for MingW.
Moving the cmath include to after the isnan fixes around the include
of algorithm.  r31355 broke the MingW build with:

vrtsources.cpp:1567: error: ‘isnan’ was not declared in this scope

Sadly, std::isnan is on in C++11 or newer.


git-svn-id: https://svn.osgeo.org/gdal/trunk@31357 f0d54148-0727-0410-94bb-9a71ac55c965