Fix change from int to bool of non-type template param from r34179.
bool bMultipleBands -> EMULATED_BOOL bMultipleBands

From the python3 build:

https://travis-ci.org/rouault/gdal_coverage/builds/128097204

overview.cpp:1465:24: error: ‘class MSVCPedanticBool’ is not a valid type for a template constant parameter
overview.cpp: In function ‘CPLErr GDALResampleChunk32R_ConvolutionT(double, double, double, double, const T*, int, GByte*, int, int, int, int, int, int, int, int, GDALRasterBand**, int, float, FilterFuncType, FilterFunc4ValuesType, int, float)’:
overview.cpp:1695:32: error: ‘bMultipleBands’ was not declared in this scope


git-svn-id: https://svn.osgeo.org/gdal/trunk@34180 f0d54148-0727-0410-94bb-9a71ac55c965